### ISSUE TITLE
Versions not updated

### ISSUE THREAD

**Issue by simon-sebold** [kube-vip/helm-charts#36]
The version of kube-vip-cloud-provider is v0.0.10 but helm chart deploys v0.0.4
The version of kube-vip is v0.8.1 but helm chart deploys v0.8.0

**Comment by rptaylor** [comment]
According to https://github.com/kube-vip/helm-charts/tags  the latest should be 0.6.2, but in the repo only 0.6.1 is available. Are the github actions not working?

```
$ helm search repo kube-vip/kube-vip --versions
NAME                            	CHART VERSION	APP VERSION	DESCRIPTION                             
kube-vip/kube-vip               	0.6.1        	v0.8.0     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.6.0        	v0.8.0     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.5.0        	v0.7.0     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.4.4        	v0.4.1     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.4.2        	v0.4.1     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.4.1        	v0.4.1     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.4.0        	v0.4.0     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.3.7        	v0.3.7     	A Helm chart for kube-vip               
kube-vip/kube-vip               	0.3.6        	v0.3.6     	A Helm chart for kube-vip               
kube-vip/kube-vip-cloud-provider	0.2.2        	v0.0.4     	A Helm chart for kube-vip cloud provider
kube-vip/kube-vip-cloud-provider	0.2.1        	v0.0.1     	A Helm chart for Kubernetes             
kube-vip/kube-vip-cloud-provider	0.2.0        	v0.0.1     	A Helm chart for Kubernetes             
kube-vip/kube-vip-cloud-provider	0.1.0        	0.1        	A Helm chart for Kubernetes             
```

**Comment by rptaylor** [comment]
It looks like all updates since about 1.5 years ago (https://github.com/kube-vip/helm-charts/commit/6e1e44fe9faaf14523faa3e72d2623a782c386d9)  have not been published in a new chart version of KV-CP. 

This can be very confusing, I was trying to figure out why the affinity was not working (https://github.com/kube-vip/helm-charts/blob/main/charts/kube-vip-cloud-provider/templates/deployment.yaml#L31) , it is just because the chart hasn't been updated.  https://github.com/kube-vip/helm-charts/issues/25 was closed but without a published chart version providing the fix.

**Comment by tecbird** [comment]
here too! please push tags to chart repo

**Comment by Fahl-Design** [comment]
@thebsdbox please take a look at this

![image](https://github.com/user-attachments/assets/b1148b50-49a3-4d0d-a45c-d6ca91c50343)

**Comment by rptaylor** [comment]
https://github.com/kube-vip/helm-charts/pull/49 did not completely fix this as intended but https://github.com/kube-vip/helm-charts/pull/54 did.
