### ISSUE TITLE
Who can tag us on kube-vip-cloud-provider and kube-vip ?

### ISSUE THREAD

**Issue by ibra-coul** [kube-vip/helm-charts#51]
We need a tag on kube-vip-cloud-provider and kube-vip

**Comment by rptaylor** [comment]
We got tags now (thank you @thebsdbox !! )  

To avoid potential confusion I think the 0.8.4 tag could be deleted https://github.com/kube-vip/helm-charts/releases/tag/kube-vip-0.8.4 , that is the app version not the chart version.

**Comment by rptaylor** [comment]
These tried to push new charts but failed:

- https://github.com/kube-vip/helm-charts/actions/runs/11400991050/job/31722982753
- https://github.com/kube-vip/helm-charts/actions/runs/11514183249/job/32052285542

**Comment by ibra-coul** [comment]
Yes you are right. I added for kube-vip-cloud-provider. But I haven't checked the kube-vip one.
I fix it right away.

**Comment by ibra-coul** [comment]
![image](https://github.com/user-attachments/assets/4b032591-57a7-4a97-93f7-d70f8f87471f)

appVersion has been updated to v0.8.4 and chart version has changed to 0.6.3
I don't know why the version chart doesn't appear in:
`helm search repo kube-vip --versions`

**Comment by rptaylor** [comment]
It is because of the failed github action runs: https://github.com/kube-vip/helm-charts/issues/51#issuecomment-2438396918

@thebsdbox do you know what the issue is with the Github actions?
